name: Build

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ '*' ]

jobs:
  build-linux:
    runs-on: ubuntu-24.04 # The image 'ubuntu-latest' pointing to ubuntu-22.04 failed because 'cmocka::cmocka' was not found.

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libboost-dev \
          libportmidi0 libportmidi-dev \
          libcmocka0 libcmocka-dev

    - name: Configure
      run: |
        cmake \
          -D WITH_TEST=ON \
          -D WITH_COVERAGE=ON \
          -S . -B build

    - name: Build
      run: |
        cmake --build build

    - name: Test
      run: |
        cd build && make test
