name: Build

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ '*' ]

jobs:
  build-linux:
    runs-on: ubuntu-24.04 # The image 'ubuntu-latest' pointing to ubuntu-22.04 failed because 'cmocka::cmocka' was not found.

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install libraries and tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libboost-dev \
          libportmidi0 libportmidi-dev \
          libcmocka0 libcmocka-dev \
          gcovr

    - name: Configure
      run: |
        cmake \
          -D WITH_TEST=ON \
          -D WITH_COVERAGE=ON \
          -S . -B build

    - name: Build
      run: |
        cmake --build build -j 5

    - name: Test
      run: |
        (cd build && make test)
        gcovr_opt=(
          -e 'test/.*'
          --exclude-throw-branches
          --exclude-unreachable-branches
        )
        gcovr "${gcovr_opt[@]}" --json-summary > gcovr-summary.json
        mkdir gcovr-details
        gcovr "${gcovr_opt[@]}" --html-details -o gcovr-details/index.html
        tar czf gcovr-details.tar.gz -C gcovr-details .
        echo '## Coverage report' >> $GITHUB_STEP_SUMMARY
        .github/scripts/gcovr-summary-to-md.py gcovr-summary.json >> $GITHUB_STEP_SUMMARY

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: gcovr-details-html
        path: |
          gcovr-details.tar.gz
